version: "3.9"
services:
  datastream: 
    image: llama
    entrypoint: python -m llama datastream
    depends_on:
      - db
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
  
  tradestream: 
    image: llama
    entrypoint: python -m llama tradestream
    depends_on:
      - db
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
  
  
  dbsetup: 
    image: llama
    entrypoint: python -m llama db upgrade
    depends_on:
      - db
    volumes:
      - ./:/app
    env_file:
      - .env
      
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data


