version: "3.9"
services:

  api: 
    image: llama
    entrypoint: python -m llama api
    depends_on:
      - db
      - dbsetup
    profiles:
      - trader
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host

  datastream: 
    image: llama
    entrypoint: python -m llama datastream
    depends_on:
      - db
      - dbsetup
    profiles:
      - trader
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host
  
  tradestream: 
    image: llama
    entrypoint: python -m llama tradestream
    profiles:
      - trader
    depends_on:
      - db
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host
  
  
  dbsetup: 
    image: llama
    entrypoint: python -m llama db upgrade
    depends_on:
      - db
    profiles:
      - trader
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host
      
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    profiles:
      - db
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - db
    profiles:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    network_mode: host