version: "3.9"
services:
  llama:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
    env_file:
      - .env
  redis:
    image: "redis:latest"
