version: "3.9"
services:

  api:
    image: llama
    entrypoint: python -m llama api
    depends_on:
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host

  datastream:
    image: llama
    entrypoint: python -m llama datastream
    depends_on:
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host

  tradestream:
    image: llama
    entrypoint: python -m llama tradestream
    depends_on:
      - db
      - dbsetup
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host


  dbsetup:
    image: llama
    entrypoint: python -m llama db upgrade
    depends_on:
      - db
    volumes:
      - ./:/app
    env_file:
      - .env
    network_mode: host

  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    profiles:
      - pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: chart@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    network_mode: host