version: "3.9"
services:
  llama:
    image: llama
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 8000:8000
  redis:
    image: "redis:latest"
