[tool.poetry]
name = "trading-bot"
version = "0.1.0"
description = ""
authors = ["Ciaran <ciaranmckey@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11"
alpaca-trade-api = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
