---
# Source: llama/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiName }}
  namespace: {{ $.Release.Namespace }}
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apiName }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiName }}
    spec:
      securityContext: {}
      imagePullSecrets:
        - name: {{ .Values.regCredName }} 
      containers:
        - name: {{ .Values.apiName }}
          volumeMounts:
            - mountPath: /secrets
              name: llama
          securityContext: null
          image: {{ .Values.imageName }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi
          command:
            - bash
            - start.sh  
            - python
            - -m
            - llama
            - api
      volumes:
        - name: llama
          secret:
            optional: false
            secretName: llama

---
# Source: llama/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiName }}
  namespace: {{ $.Release.Namespace }}
  labels: {}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.apiName }}
