---
apiVersion: batch/v1
kind: Job
metadata:
  name: llama-db-setup
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    # argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 20
      imagePullSecrets:
        - name: {{ .Values.regCredName }} 
      containers:
      - name: llama-db-setup
        volumeMounts:
          - mountPath: /secrets
            name: llama
        securityContext: null
        image: {{ .Values.imageName }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
        command:
          - python
          - -m
          - llama
          - db
          - upgrade
      restartPolicy: Never
      volumes:
        - name: llama
          secret:
            optional: false
            secretName: llama
  backoffLimit: 2
---
