---
# Source: llama/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-tradestream
  namespace: {{ $.Release.Namespace }}
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-tradestream
  template:
    metadata:
      labels:
        app: llama-tradestream
    spec:
      securityContext: {}
      imagePullSecrets:
        - name: {{ .Values.regCredName }} 
      containers:
        - name: llama-tradestream
          volumeMounts:
            - mountPath: /secrets
              name: llama
          securityContext: null
          image: {{ .Values.imageName }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi
          command:
            - python
            - -m
            - llama
            - tradestream
      volumes:
        - name: llama
          secret:
            optional: false
            secretName: llama

---