"""add extra account fields

Revision ID: 06e7e81918f0
Revises: 524dc01f1c95
Create Date: 2024-03-24 16:50:45.047249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e7e81918f0'
down_revision: Union[str, None] = '524dc01f1c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('options_buying_power', sa.String(), nullable=True), schema='llama')
    op.add_column('account', sa.Column('options_approved_level', sa.Integer(), nullable=True), schema='llama')
    op.add_column('account', sa.Column('options_trading_level', sa.Integer(), nullable=True), schema='llama')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'options_trading_level', schema='llama')
    op.drop_column('account', 'options_approved_level', schema='llama')
    op.drop_column('account', 'options_buying_power', schema='llama')
    # ### end Alembic commands ###
