"""tables

Revision ID: 2a419aff447e
Revises: 
Create Date: 2023-08-13 09:53:54.984494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a419aff447e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bars",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("vwap", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        schema="llama",
    )
    op.create_table(
        "qoutes",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("ask_exchange", sa.String(), nullable=False),
        sa.Column("ask_price", sa.Float(), nullable=False),
        sa.Column("ask_size", sa.Integer(), nullable=False),
        sa.Column("bid_exchange", sa.String(), nullable=False),
        sa.Column("bid_price", sa.Float(), nullable=False),
        sa.Column("bid_size", sa.Integer(), nullable=False),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tape", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        schema="llama",
    )
    op.create_table(
        "trades",
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tape", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        schema="llama",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades", schema="llama")
    op.drop_table("qoutes", schema="llama")
    op.drop_table("bars", schema="llama")
    # ### end Alembic commands ###
