"""change columns

Revision ID: 524dc01f1c95
Revises: 56111388690d
Create Date: 2023-10-08 20:43:35.416702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524dc01f1c95'
down_revision: Union[str, None] = '56111388690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_stats', sa.Column('buying_power', sa.Float(), nullable=False), schema='llama')
    op.add_column('backtest_stats', sa.Column('equity', sa.Float(), nullable=False), schema='llama')
    op.add_column('backtest_stats', sa.Column('starting_buying_power', sa.Float(), nullable=False), schema='llama')
    op.drop_column('backtest_stats', 'starting_balance', schema='llama')
    op.drop_column('backtest_stats', 'balance', schema='llama')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_stats', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='llama')
    op.add_column('backtest_stats', sa.Column('starting_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='llama')
    op.drop_column('backtest_stats', 'starting_buying_power', schema='llama')
    op.drop_column('backtest_stats', 'equity', schema='llama')
    op.drop_column('backtest_stats', 'buying_power', schema='llama')
    # ### end Alembic commands ###
