"""conditions

Revision ID: 643ff49b031c
Revises: 079d665567ed
Create Date: 2023-09-17 18:43:15.704584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643ff49b031c'
down_revision: Union[str, None] = '079d665567ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('default_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    schema='llama'
    )
    op.create_table('strategies',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('alias'),
    schema='llama'
    )
    op.create_table('strat_conditions',
    sa.Column('strategy_alias', sa.String(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['condition_name'], ['llama.conditions.name'], ),
    sa.ForeignKeyConstraint(['strategy_alias'], ['llama.strategies.alias'], ),
    sa.PrimaryKeyConstraint('strategy_alias', 'condition_name'),
    schema='llama'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strat_conditions', schema='llama')
    op.drop_table('strategies', schema='llama')
    op.drop_table('conditions', schema='llama')
    # ### end Alembic commands ###
