"""add technical indicators to bars

Revision ID: f1f0486d9591
Revises: 06e7e81918f0
Create Date: 2024-04-06 19:41:42.212017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f0486d9591'
down_revision: Union[str, None] = '06e7e81918f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bars', sa.Column('garman_klass_vol', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('rsi', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('bb_low', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('bb_mid', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('bb_high', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('stochastic_osci', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('sma_short', sa.Float(), nullable=True), schema='llama')
    op.add_column('bars', sa.Column('sma_long', sa.Float(), nullable=True), schema='llama')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bars', 'sma_long', schema='llama')
    op.drop_column('bars', 'sma_short', schema='llama')
    op.drop_column('bars', 'stochastic_osci', schema='llama')
    op.drop_column('bars', 'bb_high', schema='llama')
    op.drop_column('bars', 'bb_mid', schema='llama')
    op.drop_column('bars', 'bb_low', schema='llama')
    op.drop_column('bars', 'rsi', schema='llama')
    op.drop_column('bars', 'garman_klass_vol', schema='llama')
    # ### end Alembic commands ###
