"""add strat

Revision ID: fbe531239951
Revises: 643ff49b031c
Create Date: 2023-09-17 22:57:56.235748

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbe531239951'
down_revision: Union[str, None] = '643ff49b031c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='llama')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'strategies', schema='llama')
    # ### end Alembic commands ###
