on:
  push:
    branches:
      - master

jobs:
  scan-build-push-workflow:
    uses: ${{ github.repository_owner }}/ops/.github/workflows/python-docker-workflow.yaml@master
    secrets:
      CONTAINER_PAT: ${{ secrets.CONTAINER_PAT }}