name: Build and Push Image

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you require

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="/root/.local/bin:$PATH"
          poetry config virtualenvs.create false
          poetry install

      - name: Run Pylint
        run: |
          pylint --fail-under=8 ./**/*.py

      - name: Run mypy
        run: |
          mypy ./
      
      - name: Run ruff
        run: |
          ruff ./
  build-and-push:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_PAT }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix={{branch}}-{{tag}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  
  container-scan:
    needs: build-and-push
    
    runs-on: ubuntu-latest
    
    steps:

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix={{branch}}-{{tag}}
      
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          
      - name: Scan container image
        run: |
          trivy ${{ steps.meta.outputs.tags }}