on:
  push:
    branches:
      - master

jobs:
  scan-build-push-workflow:
    runs-on: self-hosted
    uses: 1ndistinct/ops/.github/workflows/python-docker-workflow-self-hosted.yaml@master
    secrets:
      CONTAINER_PAT: ${{ secrets.CONTAINER_PAT }}